# Generated by Django 2.2 on 2020-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='sizes', max_length=120),
        ),
    ]
