# Generated by Django 2.2 on 2020-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productoptions_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='Variation',
        ),
    ]
